import axios from 'axios';
import Head from 'next/head';

import styles from '../styles/Home.module.css';
import { EventGood } from './components/eventgood.component';

import type {EventGoodType} from './api/eventgoods';

import type {NextPage} from 'next';
interface HomeProps {
  eventgoods: EventGoodType[];
}

const Home: NextPage<HomeProps> = (props: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Convenience Store Promotion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Convenience Store Promotion</h1>
        <ul>
          {props.eventgoods.map((good) => (
            <EventGood key={good.productName} eventgood={good} />
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;

export async function getStaticProps(): Promise<{props: HomeProps}> {
  try {
    const res = await axios.get(`http://localhost:3000/api/eventgoods`);
    const data = res.data;
    return {
      props: {
        eventgoods: data,
      },
    };
  } catch (e) {
    console.error(`ERROR`);
    throw e;
  }
}
