import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Convenience Store Promotion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Convenience Store Promotion
        </h1>
        <ul>
          <li>
            <div>
              <div>
                <img src="" alt="" />
              </div>
              <h4>제품명이 여기</h4>
              <p>
                <span>가격</span>
                <span>15,000원</span>
              </p>
            </div>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
